FLS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

BLS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

RS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

REA:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12
    pop_size: 10
    tournament_size: 10
    prob_mutation: 1.0

REA+W:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12
    pop_size: 10
    tournament_size: 10
    prob_mutation: 1.0
    warm_up: True
    n_sample_warmup: 2000
    metric_warmup: synflow