MF-NAS:
    # stage 1
    optimizer_stage1: FLS
    using_zc_metric_stage1: True
    metric_stage1: ['grad_norm', 'jacov', 'plain', 'zen']
    max_eval_stage1: 2000

    # stage 2
    using_zc_metric_stage2: False
    metric_stage2: val_acc
    list_iepoch: [20, 40, 60, 80, 100]
    n_candidate: 32
