MF-NAS:
    # stage 1
    optimizer_stage1: FLS
    using_zc_metric_stage1: True
    metric_stage1: params
    max_eval_stage1: 2000

    # stage 2
    using_zc_metric_stage2: False
    metric_stage2: val_acc
    list_iepoch: [25, 50, 75, 100]
    n_candidate: 16
