FLS:
  using_zc_metric: false
  metric: val_per
  iepoch: 12
BLS:
  using_zc_metric: false
  metric: val_per
  iepoch: 12
RS:
  using_zc_metric: false
  metric: val_per
  iepoch: 12
REA:
  using_zc_metric: false
  metric: val_per
  iepoch: 12
  pop_size: 10
  tournament_size: 10
  prob_mutation: 1.0
REA+W:
  using_zc_metric: false
  metric: val_per
  iepoch: 12
  pop_size: 10
  tournament_size: 10
  prob_mutation: 1.0
  warm_up: true
  n_sample_warmup: 2000
  metric_warmup: synflow
SH:
  using_zc_metric: false
  metric: val_per
  list_iepoch:
  - 10
  - 20
  - 30
  - 40
  n_candidate: 16
MF-NAS:
  optimizer_stage1: FLS
  using_zc_metric_stage1: true
  metric_stage1: synflow
  max_eval_stage1: 2000
  using_zc_metric_stage2: false
  metric_stage2: val_per
  list_iepoch:
  - 10
  - 20
  - 30
  - 40
  n_candidate: '16'
R-MF-NAS:
  optimizer_stage1: FLS
  using_zc_metric_stage1: true
  metric_stage1: synflow
  max_eval_stage1: 2000
  using_zc_metric_stage2: false
  metric_stage2: val_per
  list_iepoch:
  - 10
  - 20
  - 30
  - 40
  n_candidate: '16'
NSGA2:
  need_trained:
  - true
  - false
  list_metrics:
  - val_per
  - params
  list_iepochs:
  - 12
  - 0
  pop_size: 20
  crossover_method: 2X
  prob_c: 0.9
  prob_m: 1.0
