FLS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

BLS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

RS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

REA:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12
    pop_size: 10
    tournament_size: 10
    prob_mutation: 1.0

GA:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12
    pop_size: 10
    tournament_size: 10
    prob_mutation: 1.0

REA+W:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12
    pop_size: 10
    tournament_size: 10
    prob_mutation: 1.0
    warm_up: True
    n_sample_warmup: 2000
    metric_warmup: synflow

SH:
    using_zc_metric: False
    metric: val_acc
    list_iepoch: [12, 25, 50, 100, 200]
    n_candidate: 32

MF-NAS:
    # stage 1
    metric_stage1: params
    optimizer_stage1: FLS  # choices: [FLS, BLS]
    using_zc_metric_stage1: True
    max_eval_stage1: 2000

    # stage 2
    using_zc_metric_stage2: False
    metric_stage2: val_acc
    list_iepoch: [12, 25, 50, 100, 200]
    n_candidate: 32
