FLS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

BLS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

RS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

REA:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12
    pop_size: 20
    tournament_size: 4
    prob_mutation: 1.0

GA:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12
    pop_size: 10
    tournament_size: 4
    prob_mutation: 1.0
    crossover_method: 2X
    prob_crossover: 0.9

MF-GA:
    using_zc_metric: False
    metric: val_acc
    pop_size: 20
    tournament_size: 4
    prob_mutation: 1.0
    crossover_method: 2X
    prob_crossover: 0.9
    init_epoch: 4
    step: 4

REA+W:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12
    pop_size: 20
    tournament_size: 4
    prob_mutation: 1.0
    warm_up: True
    n_sample_warmup: 2000
    metric_warmup: synflow

SH:
    using_zc_metric: False
    metric: val_acc
    list_iepoch: [12, 25, 50, 100, 200]
    n_candidate: 32

MF-NAS:
    # stage 1
    metric_stage1: params
    optimizer_stage1: FLS  # choices: [FLS, BLS]
    using_zc_metric_stage1: True
    max_eval_stage1: 2000

    # stage 2
    using_zc_metric_stage2: False
    metric_stage2: val_acc
    list_iepoch: [12, 25, 50, 100, 200]
    n_candidate: 32

LOMONAS:
    using_zc_metrics: [False, True]
    metrics: [val_error, flops]
    iepochs: [12, 0]
    k: 3

NSGA2:
    using_zc_metrics: [False, True]
    metrics: [val_error, flops]
    iepochs: [12, 0]
    pop_size: 20
    prob_mutation: 1.0
    crossover_method: 2X
    prob_crossover: 0.9