FLS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

BLS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

RS:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12

REA:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12
    pop_size: 10
    tournament_size: 10
    prob_mutation: 1.0

REA+W:
    using_zc_metric: False
    metric: val_acc
    iepoch: 12
    pop_size: 10
    tournament_size: 10
    prob_mutation: 1.0
    warm_up: True
    n_sample_warmup: 2000
    metric_warmup: synflow  # choices: [synflow, flops, params]

SH:
    using_zc_metric: False
    metric: val_acc
    list_iepoch: [4, 12, 36, 108]
    n_candidate: 16

MF-NAS:
    # stage 1
    optimizer_stage1: FLS  # choices: [FLS, BLS]
    using_zc_metric_stage1: True
    metric_stage1: params  # choices: [synflow, flops, params]
    max_eval_stage1: 2000

    # stage 2
    using_zc_metric_stage2: False
    metric_stage2: val_acc
    list_iepoch: [4, 12, 36, 108]
    n_candidate: 16
