nb201_cifar10:
    max_time: 9999999999
    max_eval: 9999999999
    dataset: cifar10
    mo_objective: [err, flops]

nb201_cifar100:
    max_time: 9999999999
    max_eval: 9999999999
    dataset: cifar100
    mo_objective: [err, flops]

nb201_ImageNet16-120:
    max_time: 9999999999
    max_eval: 9999999999
    dataset: ImageNet16-120
    mo_objective: [err, flops]

nb101:
    max_time: 9999999999
    max_eval: 9999999999
    dataset: cifar10
    mo_objective: [err, params]

nbasr:
    max_time: 9999999999
    max_eval: 25
    dataset: TIMIT
    mo_objective: [err, flops]

nats_cifar10:
    max_time: 9999999999
    max_eval: 9999999999
    dataset: cifar10
    mo_objective: [err, flops]

nats_cifar100:
    max_time: 9999999999
    max_eval: 9999999999
    dataset: cifar100
    mo_objective: [err, flops]

nats_ImageNet16-120:
    max_time: 9999999999
    max_eval: 9999999999
    dataset: ImageNet16-120
    mo_objective: [err, flops]

darts:
    max_time: 9999999999
    max_eval: 9999999999
    dataset: cifar10
    n_models_per_train: 32
    using_ray: False

    max_epoch: 600
    drop_path_prob: 0.3
    learning_rate: 0.025
    momentum: 0.9
    weight_decay: 0.0003
    batch_size: 64
    train_portion: 0.5
    auxiliary: True
    auxiliary_weight: 0.4
    grad_clip: 5
